channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - ipykernel
  - xarray
  - dask
  - netCDF4
  - bottleneck
  - cudatoolkit=11.2
  - pip:
    - "matplotlib<3.4"
    - omegaconf
    - pandas
    - numpy
    - seaborn
    - tqdm
    - scipy
    - scikit-learn
    - scikit-image
    - joblib
    - tensorflow-gpu
    - tensorflow-addons
    - hydra-core

